#!/bin/sh

# Keep package lists up to date
chronic /usr/bin/apt-get -qq update
/usr/bin/debtags update
/usr/sbin/update-pciids -q
/usr/sbin/update-usbids -q
chronic /usr/sbin/update-command-not-found

# Pre-download packages (to speed up manual updates)
/usr/bin/apt-get -qq clean
chronic /usr/bin/apt-get --download-only --assume-yes --force-yes -qq dist-upgrade

# Remove unnecessary debs from the cache
/usr/bin/apt-get -qq autoclean

# Rebuild dpkg database
# (see http://antti-juhani.kaijanaho.fi/newblog/archives/521)
/usr/bin/dpkg --clear-avail
/usr/sbin/sync-available > /dev/null
