#!/bin/sh

# Keep package lists up to date
/usr/bin/apt-get -qq update > /dev/null 2>&1
/usr/bin/debtags update
/usr/sbin/update-pciids -q
/usr/sbin/update-command-not-found > /dev/null 2>&1

# Pre-download packages (to speed up manual updates)
/usr/bin/apt-get -qq clean
chronic /usr/bin/apt-get --download-only --assume-yes --force-yes -qq dist-upgrade

# Remove unnecessary debs from the cache
/usr/bin/apt-get -qq autoclean

# Rebuild dpkg database
# (see http://antti-juhani.kaijanaho.fi/newblog/archives/521)
/usr/bin/dpkg --clear-avail
/usr/sbin/sync-available > /dev/null

# Look for obsolete config files
# https://lists.debian.org/debian-mentors/2013/05/msg00115.html
# shellcheck disable=SC2016
dpkg-query -W -f='${Conffiles}\n' | grep 'obsolete$'

# Look for removed (but not purged) packages
dpkg -l | grep -i '^rc\s.*$'

# Swallow error codes (rely on output to stdout/stderr)
/bin/true
