#!/bin/bash
#
# Usage:
#
#    cpufreq
#    cpufreq performance
#    cpufreq powersave

if [ "z$1" = "z" ] ; then
    cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
    exit 0
fi

VALID="$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors)"
for valid in $VALID ; do
    if [ "$1" = "$valid" ] ; then
        for cpu in /sys/devices/system/cpu/cpu[0-9]* ; do
            echo "$valid" > "$cpu/cpufreq/scaling_governor"
        done
        exit 0
    fi
done

echo "Invalid parameter. Valid governors are: $VALID"
exit 1
