#!/bin/bash

if lockfile /var/lock/partition-boot ; then
    umount /boot
    /usr/bin/chronic /sbin/fsck.ext4 -p -f -c /dev/disk/by-uuid/20aa2da0-d6d8-4eac-976c-17aff66b442b || true
    /bin/mount /boot || echo "Cannot re-mount /boot"
    rm -f /var/lock/partition-boot
else
    echo "Cannot get the lock for /boot, skipping fsck."
fi

if lockfile /var/lock/partition-mnt-boot ; then
    umount /mnt/boot
    /usr/bin/chronic /sbin/fsck.ext4 -p -f -c /dev/disk/by-uuid/ceaedca4-0611-460d-9139-5cfa65465fec || true
    /bin/mount /mnt/boot || echo "Cannot re-mount /mnt/boot"
    rm -f /var/lock/partition-mnt-boot
else
    echo "Cannot get the lock for /mnt/boot, skipping fsck."
fi
