#!/bin/bash

if lockfile -r 8 /var/lock/partition-boot ; then
    echo "Remounting /boot as rw before dpkg run"
    touch /var/lock/partition-boot.remount-boot-rw
    mount -o remount,rw /boot
else
    echo "Cannot re-mount /boot rw"
    exit 1
fi
