#!/bin/bash

rm -f /var/lock/partition-boot /var/lock/partition-boot.remount-boot-rw
echo "Remounting /boot as ro after dpkg run"
if ! mount -o remount,ro /boot ; then
    echo "Cannot re-mount /boot ro"
    exit 1
fi
